### ISSUE TITLE
ItemStages: Internal Server Error

### ISSUE THREAD

**Issue by artdude543** [Darkhax-Minecraft/ItemStages#14]
While testing a server update for SevTech: Ages (3.0.2) a player right clicked a block (Immersive Chest) to which they was booted from the game and the server logged the following: 

```
[11:51:15] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.living.LivingEvent$LivingUpdateEvent@3f42ae64:
java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at net.darkhax.itemstages.ItemStages.getUnfamiliarName(ItemStages.java:80) ~[ItemStages.class:?]
	at net.darkhax.itemstages.ItemStages.sendDropMessage(ItemStages.java:85) ~[ItemStages.class:?]
	at net.darkhax.itemstages.ItemStages.onLivingUpdate(ItemStages.java:155) ~[ItemStages.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1063_ItemStages_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) [EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:556) [ForgeHooks.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2086) [vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) [aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) [oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) [pa.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) [NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) [gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.I18n
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
	... 19 more
[11:51:15] [Server thread/ERROR] [FML]: Index: 30 Listeners:
[11:51:15] [Server thread/ERROR] [FML]: 0: HIGHEST
[11:51:15] [Server thread/ERROR] [FML]: 1: ASM: class WayofTime.bloodmagic.util.handler.event.LivingArmourHandler onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 2: ASM: hellfirepvp.astralsorcery.common.util.effect.time.TimeStopController@30ecf941 onLivingTickTest(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 3: NORMAL
[11:51:15] [Server thread/ERROR] [FML]: 4: ASM: class betterwithmods.event.PotionEventHandler onPotionUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 5: ASM: class WayofTime.bloodmagic.util.handler.event.GenericHandler onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 6: ASM: class WayofTime.bloodmagic.potion.PotionEventHandlers onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 7: ASM: net.darkhax.darkutils.features.misc.FeatureSheepArmor@44e430c8 onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 8: ASM: net.darkhax.darkutils.features.shulkerpearl.FeatureShulkerPearlItem@64faf164 onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 9: ASM: class flaxbeard.immersivepetroleum.common.EventHandler test(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 10: ASM: class nex.handler.EventHandler onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 11: ASM: class twilightforest.TFEventListener livingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)Z
[11:51:15] [Server thread/ERROR] [FML]: 12: ASM: com.shinoow.abyssalcraft.common.handlers.AbyssalCraftEventHooks@2e3daece darkRealm(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 13: ASM: com.shinoow.abyssalcraft.common.handlers.KnowledgeEventHandler@7eae7b46 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 14: ASM: betterwithmods.module.gameplay.breeding_harness.BreedingHarness@6553feef onLivingTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 15: ASM: vazkii.quark.misc.feature.PoisonPotatoUsage@41edcaa2 onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 16: ASM: vazkii.quark.world.feature.Biotite@300f743f onEntityTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 17: ASM: vazkii.quark.tweaks.feature.BabyZombiesBurn@5da9f079 entityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 18: ASM: vazkii.quark.tweaks.feature.SheepArmor@8753d2b onUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 19: ASM: vazkii.quark.tweaks.feature.LookDownLadders@29247319 onPlayerTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 20: ASM: vazkii.quark.tweaks.feature.ChickensShedFeathers@2dbba2e2 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 21: ASM: betterwithaddons.handler.AssortedHandler@74fa1256 livingTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 22: ASM: tschipp.carryon.common.event.ItemEntityEvents@2a046ff4 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 23: ASM: class death_compass.capabilities.base.EntityCapabilityHandler onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 24: ASM: micdoodle8.mods.galacticraft.core.event.EventHandlerGC@16c892b4 entityLivingEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 25: ASM: com.mjr.extraplanets.handlers.MainHandlerServer@1b87b8cb onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 26: ASM: net.darkhax.huntingdim.handler.DimensionEffectHandler@3707e3c onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 27: ASM: net.darkhax.huntingdim.handler.DimensionEffectHandler@3707e3c onEntityJoinWorld(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 28: ASM: com.buuz135.industrial.proxy.event.MeatFeederTickHandler@6042fd85 onTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 29: ASM: cpw.mods.ironchest.common.util.OcelotsSitOnChestsHandler@5aa0daa3 changeSittingTaskForOcelots(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 30: ASM: net.darkhax.itemstages.ItemStages@2f155a4b onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 31: ASM: class mob_grinding_utils.capability.base.EntityCapabilityHandler onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 32: ASM: com.blakebr0.mysticalagriculture.items.armor.ItemIntermediumArmor$AbilityHandler@7c9ac1e9 updatePlayerAbilityStatus(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 33: ASM: com.blakebr0.mysticalagriculture.items.armor.ItemSuperiumArmor$AbilityHandler@e4be098 updatePlayerAbilityStatus(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 34: ASM: com.blakebr0.mysticalagriculture.items.armor.ItemSupremiumArmor$AbilityHandler@636a0c57 updatePlayerAbilityStatus(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 35: ASM: com.blakebr0.pickletweaks.feature.item.ItemNightvisionGoggles$Handler@4f3b20aa giveNightvision(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 36: ASM: rustic.common.EventHandlerCommon@2d009534 onChickenUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 37: ASM: com.shinoow.beneath.common.handler.BeneathEventHandler@4516c8d5 darkness(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 38: ASM: net.darkhax.tinkerstages.TinkerStages@78e2d74c onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 39: ASM: de.ellpeck.actuallyadditions.mod.items.ItemWingsOfTheBats@743794c livingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 40: ASM: de.ellpeck.actuallyadditions.mod.items.ItemHairyBall@1d537a37 livingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 41: ASM: blusunrize.immersiveengineering.common.EventHandler@4b4f0044 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 42: ASM: squeek.appleskin.network.SyncHandler@cb5020b onLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 43: ASM: com.lothrazar.cyclicmagic.component.playerext.EventExtendedInventory@35c5fb59 playerTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 44: ASM: com.lothrazar.cyclicmagic.potion.EventPotionTick@2c5ca750 onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 45: ASM: Block{cyclicmagic:plate_vector} onUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 46: ASM: com.lothrazar.cyclicmagic.item.food.ItemAppleStep@6b3a0a83 onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 47: ASM: com.lothrazar.cyclicmagic.item.food.ItemChorusCorrupted@fa3cad1 onPlayerUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 48: ASM: com.lothrazar.cyclicmagic.item.food.ItemChorusGlowing@fd0fcfd onPlayerUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 49: ASM: com.lothrazar.cyclicmagic.item.gear.ItemGlowingHelmet@6a0a6cfc onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 50: ASM: com.lothrazar.cyclicmagic.enchantment.EnchantWaterwalking@2b7c4538 onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 51: ASM: com.lothrazar.cyclicmagic.enchantment.EnchantReach@4b166f7f onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 52: ASM: com.lothrazar.cyclicmagic.enchantment.EnchantLaunch@3c6401e8 onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 53: ASM: com.lothrazar.cyclicmagic.enchantment.EnchantMagnet@44f1fc8c onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 54: ASM: com.lothrazar.cyclicmagic.enchantment.EnchantQuickdraw@2d5eb976 onPlayerUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 55: ASM: com.lothrazar.cyclicmagic.module.PlayerAbilitiesModule@697a2ff8 onPlayerTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 56: ASM: com.lothrazar.cyclicmagic.module.FragileTorchesModule@97e725e onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 57: ASM: com.lothrazar.cyclicmagic.module.MountedTweaksModule@54f0849 onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 58: ASM: com.cjm721.overloaded.item.functional.armor.ArmorEventHandler@1ed0a300 onLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 59: ASM: class thebetweenlands.common.handler.PuppetHandler onUpdateLiving(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 60: ASM: class thebetweenlands.common.handler.PlayerPortalHandler teleportCheck(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 61: ASM: thebetweenlands.common.handler.ElixirCommonHandler@6785abce onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 62: ASM: class thebetweenlands.common.block.plant.BlockWeedwoodBush onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 63: ASM: thretcha.roadrunner.RoadHandler@4060ee4c livingEntityOnRoad(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 64: ASM: pokefenn.totemic.handler.EntityUpdate@e04a5d5 onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 65: ASM: mob_grinding_utils.events.ChickenFuseEvent@1f1949e8 startChickenFuse(Lnet/minecraftforge/event/entity/living/LivingEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 66: LOW
[11:51:15] [Server thread/ERROR] [FML]: 67: ASM: class nmd.primal.core.common.events.EntityEvents onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/ERROR] [FML]: 68: ASM: class nmd.primal.core.common.init.ModPotions$RegistrationHandler onPotionUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
[11:51:15] [Server thread/WARN] [net.minecraft.network.NetworkSystem]: Failed to handle packet for /cheesecakes
net.minecraft.util.ReportedException: Ticking player
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:459) ~[oq.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) ~[pa.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/resources/I18n
	at net.darkhax.itemstages.ItemStages.getUnfamiliarName(ItemStages.java:80) ~[ItemStages.class:?]
	at net.darkhax.itemstages.ItemStages.sendDropMessage(ItemStages.java:85) ~[ItemStages.class:?]
	at net.darkhax.itemstages.ItemStages.onLivingUpdate(ItemStages.java:155) ~[ItemStages.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1063_ItemStages_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:556) ~[ForgeHooks.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2086) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
	... 9 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.resources.I18n
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
	at net.darkhax.itemstages.ItemStages.getUnfamiliarName(ItemStages.java:80) ~[ItemStages.class:?]
	at net.darkhax.itemstages.ItemStages.sendDropMessage(ItemStages.java:85) ~[ItemStages.class:?]
	at net.darkhax.itemstages.ItemStages.onLivingUpdate(ItemStages.java:155) ~[ItemStages.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1063_ItemStages_onLivingUpdate_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:556) ~[ForgeHooks.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2086) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234) ~[aed.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) ~[oq.class:?]
	... 9 more
[11:51:15] [Server thread/INFO] [net.minecraft.network.NetHandlerPlayServer]: artdude543 lost connection: Internal server error
```

Seems Client Side methods is being called Server side.

**Comment by artdude543** [comment]
This also prevents any player with the issue from re-joining the server.

**Comment by darkhax** [comment]
This should now be fixed.

**Comment by artdude543** [comment]
Thanks!
